### ISSUE TITLE
White boarder on XFCE4 Terminal

### ISSUE THREAD

**Issue by CarterSnich** [dmuellner/mist-redmond-green#1]
How can I remove this white border on XFCE terminal? I use i3. It's hard to know which window is active with the white boarders.
![2024-12-06_21-20](https://github.com/user-attachments/assets/c34ffaa4-a3fe-4fec-9064-fc6e58e73f91)

It should look like this (when using other themes, including the original Mist):
![2024-12-06_21-23](https://github.com/user-attachments/assets/9909a43c-f530-436f-832b-94ce23d212bb)

I'm using mist redmond green version 1.1.

**Comment by dmuellner** [comment]
Sorry, I don't have experience with i3. If you find a solution, please let me know the fix.

**Comment by CarterSnich** [comment]
I don't think it's related to i3. I think it's the padding between the terminal canvas and the window. I don't know anything about creating GTK themes.
